name: Test application

on:
    pull_request:
    push:
        branches:
          - '[0-9]+.x'
          - '[0-9]+.[0-9]+'

jobs:
    test:
        name: "Run tests with php ${{ matrix.php-version }}"
        runs-on: ubuntu-latest

        env:
            SYMFONY__DATABASE__DRIVER: pdo_mysql
            SYMFONY__DATABASE__VERSION: 5.7
            SYMFONY__DATABASE__HOST: 127.0.0.1
            SYMFONY__DATABASE__PORT: 3306
            SYMFONY__DATABASE__NAME: sulu_test
            SYMFONY__DATABASE__USER: root
            SYMFONY__DATABASE__PASSWORD: root

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '5.5'
                      # --prefer-lowest not possible in sulu 1.3
                      composer-flags: '--prefer-dist --no-interaction'
                      tools: 'composer:v1'
                      lint: false
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: disabled
                    - php-version: '7.4'
                      composer-flags: '--prefer-dist --no-interaction'
                      tools: 'composer:v2'
                      lint: true
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: 'mysql, gd'
                  tools: ${{ matrix.tools }}

            - name: Get composer cache directory
              id: composer-cache-dir
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                path: ${{ steps.composer-cache-dir.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('composer.json', 'composer.lock') }}
                restore-keys: |
                  ${{ runner.os }}-composer-

            - name: Install dependencies
              run: |
                  composer validate --strict
                  composer update ${{ matrix.composer-flags }}

            - name: Create database
              run: |
                  ./Tests/app/console doctrine:database:create
                  ./Tests/app/console doctrine:schema:update --force
              env: ${{ matrix.env }}

            - name: Lint Code
              if: ${{ matrix.lint }}
              run: |
                  ./Tests/app/console lint:twig Resources/views --env test
                  ./Tests/app/console sulu:community:init -vvv --env test
              env: ${{ matrix.env }}

            - name: Execute test cases
              run: time vendor/bin/phpunit
              env: ${{ matrix.env }}
